---
include:
- "../../fastlane/settings.yml"
name: UserService
settings:
  groups:
  - BaseProjectSetting
targets:
  UserService:
    type: framework
    platform: iOS
    sources: UserService
    scheme:
      testTargets:
      - UserServiceTests
      gatherCoverageData: true
    settings:
      groups:
      - BaseTargetSetting
  UserServiceTests:
    type: bundle.unit-test
    platform: iOS
    sources:
    - path: UserServiceTests
    dependencies:
    - target: UserService
    settings:
      groups:
        - BaseTargetSetting
        - BaseTestTargetSetting

